jQuery(document).ready(function($){$.fn.exists=function(){if($(this).length>0){return true;}else{return false;}}
$.fn.loaded=function(callback,jointCallback,ensureCallback){var len=this.length;if(len>0){return this.each(function(){var el=this,$el=$(el),blank="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw==";$el.on("load.dt",function(event){$(this).off("load.dt");if(typeof callback=="function"){callback.call(this);}
if(--len<=0&&(typeof jointCallback=="function")){jointCallback.call(this);}});if(!el.complete||el.complete===undefined){el.src=el.src;}else{$el.trigger("load.dt")}});}else if(ensureCallback){if(typeof jointCallback=="function"){jointCallback.call(this);}
return this;}};var $body=$("body"),$window=$(window),$mainSlider=$('#main-slideshow'),adminH=$('#wpadminbar').height(),header=$('.masthead:not(.side-header):not(.side-header-v-stroke)').height(),bodyTransparent=$body.hasClass("transparent"),headerBelowSliderExists=$(".floating-navigation-below-slider").exists(),$mastheadHeader=$(".masthead");if($body.hasClass("transparent")){var headerH=0;}else if($body.hasClass("overlap")){var headerH=($('.masthead:not(.side-header):not(.side-header-v-stroke)').height()+(parseInt($mainSlider.css("marginTop"))+parseInt($mainSlider.css("marginBottom"))));}else{var headerH=$('.masthead:not(.side-header):not(.side-header-v-stroke)').height();}
'use strict';$.HoverDir=function(options,element){this.$el=$(element);this._init(options);};$.HoverDir.defaults={speed:300,easing:'ease',hoverDelay:0,inverse:false};$.HoverDir.prototype={_init:function(options){this.options=$.extend(true,{},$.HoverDir.defaults,options);this.transitionProp='all '+this.options.speed+'ms '+this.options.easing;this.support=Modernizr.csstransitions;this._loadEvents();},_loadEvents:function(){var self=this;this.$el.on('mouseenter.hoverdir, mouseleave.hoverdir',function(event){var $el=$(this),$hoverElem=$el.find('.rollover-content, .post-entry-content'),direction=self._getDir($el,{x:event.pageX,y:event.pageY}),styleCSS=self._getStyle(direction);if(event.type==='mouseenter'){$hoverElem.hide().css(styleCSS.from);clearTimeout(self.tmhover);self.tmhover=setTimeout(function(){$hoverElem.show(0,function(){var $el=$(this);if(self.support){$el.css('transition',self.transitionProp);}
self._applyAnimation($el,styleCSS.to,self.options.speed);});},self.options.hoverDelay);}
else{if(self.support){$hoverElem.css('transition',self.transitionProp);}
clearTimeout(self.tmhover);self._applyAnimation($hoverElem,styleCSS.from,self.options.speed);}});},_getDir:function($el,coordinates){var w=$el.width(),h=$el.height(),x=(coordinates.x-$el.offset().left-(w/2))*(w>h?(h/w):1),y=(coordinates.y-$el.offset().top-(h/2))*(h>w?(w/h):1),direction=Math.round((((Math.atan2(y,x)*(180/Math.PI))+180)/90)+3)%4;return direction;},_getStyle:function(direction){var fromStyle,toStyle,slideFromTop={left:'0px',top:'-100%'},slideFromBottom={left:'0px',top:'100%'},slideFromLeft={left:'-100%',top:'0px'},slideFromRight={left:'100%',top:'0px'},slideTop={top:'0px'},slideLeft={left:'0px'};switch(direction){case 0:fromStyle=!this.options.inverse?slideFromTop:slideFromBottom;toStyle=slideTop;break;case 1:fromStyle=!this.options.inverse?slideFromRight:slideFromLeft;toStyle=slideLeft;break;case 2:fromStyle=!this.options.inverse?slideFromBottom:slideFromTop;toStyle=slideTop;break;case 3:fromStyle=!this.options.inverse?slideFromLeft:slideFromRight;toStyle=slideLeft;break;};return{from:fromStyle,to:toStyle};},_applyAnimation:function(el,styleCSS,speed){$.fn.applyStyle=this.support?$.fn.css:$.fn.animate;el.stop().applyStyle(styleCSS,$.extend(true,[],{duration:speed+'ms'}));},};var logError=function(message){if(window.console){window.console.error(message);}};$.fn.hoverdir=function(options){var instance=$.data(this,'hoverdir');if(typeof options==='string'){var args=Array.prototype.slice.call(arguments,1);this.each(function(){if(!instance){logError("cannot call methods on hoverdir prior to initialization; "+
"attempted to call method '"+options+"'");return;}
if(!$.isFunction(instance[options])||options.charAt(0)==="_"){logError("no such method '"+options+"' for hoverdir instance");return;}
instance[options].apply(instance,args);});}
else{this.each(function(){if(instance){instance._init();}
else{instance=$.data(this,'hoverdir',new $.HoverDir(options,this));}});}
return instance;};/*!-Hover Direction aware init*/$('.mobile-false .hover-grid .rollover-project, .mobile-false .hover-grid.portfolio-shortcode .post').each(function(){$(this).hoverdir();});$('.mobile-false .hover-grid-reverse .rollover-project, .mobile-false .hover-grid-reverse.portfolio-shortcode .post ').each(function(){$(this).hoverdir({inverse:true});});/*!Append tag </span> for portfolio round links button*/$.fn.hoverLinks=function(){if($(".semitransparent-portfolio-icons").length>0||$(".accent-portfolio-icons").length>0){return this.each(function(){var $img=$(this),iconHoverTimer;if($img.hasClass("height-ready")){return;}
$("<span/>").appendTo($(this));$img.on({mouseenter:function(){if(0===$(this).children("span").length){var a=$("<span/>").appendTo($(this));clearTimeout(iconHoverTimer);iconHoverTimer=setTimeout(function(){a.addClass("icon-hover")},20)}else $(this).children("span").addClass("icon-hover")},mouseleave:function(){$(this).children("span").removeClass("icon-hover")}});$img.addClass("height-ready");});}};$(".links-container a").hoverLinks();$.fn.addIconToLinks=function(){return this.each(function(){var $icon=$(this);if($icon.hasClass("icon-ready")){return;}
$("<span/>").appendTo($(this));$icon.addClass("icon-ready");});};$(".project-links-container a").addIconToLinks();/*!Trigger click (direct to post)*/$.fn.forwardToPost=function(){return this.each(function(){var $this=$(this);if($this.hasClass("this-ready")){return;};$this.on("click",function(){if($this.parents(".ts-wrap").hasClass("ts-interceptClicks"))return;window.location.href=$this.find("a").first().attr("href");return false;});$this.addClass("this-ready");});};$(".mobile-false .rollover-project.forward-post").forwardToPost();$.fn.touchforwardToPost=function(){return this.each(function(){var $this=$(this);if($this.hasClass("touch-hover-ready")){return;}
$body.on("touchend",function(e){$(".mobile-true .rollover-content").removeClass("is-clicked");$(".mobile-true .rollover-project").removeClass("is-clicked");});var $this=$(this).find(".rollover-content");$this.on("touchstart",function(e){origY=e.originalEvent.touches[0].pageY;origX=e.originalEvent.touches[0].pageX;});$this.on("touchend",function(e){var touchEX=e.originalEvent.changedTouches[0].pageX,touchEY=e.originalEvent.changedTouches[0].pageY;if(origY==touchEY||origX==touchEX){if($this.hasClass("is-clicked")){window.location.href=$this.prev("a").first().attr("href");}else{e.preventDefault();$(".mobile-ture .rollover-content").removeClass("is-clicked");$(".mobile-true .rollover-project").removeClass("is-clicked");$this.addClass("is-clicked");$this.parent(".rollover-project").addClass("is-clicked");return false;};};});$this.addClass("touch-hover-ready");});};$(".mobile-true .rollover-project.forward-post").touchforwardToPost();/*!Trigger click on portfolio hover buttons*/$.fn.followCurentLink=function(){return this.each(function(){if($(this).parents('.content-rollover-layout-list').length>0||$(this).parents('.gradient-overlay-layout-list').length>0){var $this=$(this).parent('article');}else{var $this=$(this);}
if($this.hasClass("this-ready")){return;}
var $thisSingleLink=$this.parent().find(".links-container > a, .project-links-container > a"),$thisCategory=$this.find(".portfolio-categories a"),$thisReadMore=$this.find(".post-details");var alreadyTriggered=false;$this.on("click",function(){if($this.parents(".ts-wrap").hasClass("ts-interceptClicks"))return;$thisSingleLink.each(function(){$thisTarget=$(this).attr("target")?$(this).attr("target"):"_self";});if($thisSingleLink.hasClass("project-details")||$thisSingleLink.hasClass("link")||$thisSingleLink.hasClass("project-link")){window.open($thisSingleLink.attr("href"),$thisTarget);return false;}else{if(!alreadyTriggered){alreadyTriggered=true;$thisSingleLink.trigger("click");alreadyTriggered=false;}
return false;}});$this.find($thisCategory).click(function(e){e.stopPropagation();window.location.href=$thisCategory.attr('href');});var $thisTarget=(typeof $thisReadMore.attr("target")!='undefined'&&$thisReadMore.attr("target").length>0)?$thisReadMore.attr("target"):"_self";$this.find($thisReadMore).click(function(e){e.stopPropagation();e.preventDefault();window.open($thisReadMore.attr('href'),$thisTarget);});$this.addClass("this-ready");});};$(".mobile-false .rollover-project.rollover-active, .mobile-false .rollover-active,  .mobile-false .buttons-on-img.rollover-active").followCurentLink();$.fn.touchFollowCurentLink=function(){return this.each(function(){if($(this).parents('.content-rollover-layout-list').length>0||$(this).parents('.gradient-overlay-layout-list').length>0){var $this=$(this).parent('article');}else{var $this=$(this);}
if($this.hasClass("this-ready")){return;}
var $thisSingleLink=$this.parent().find(".links-container > a, .project-links-container > a"),$thisCategory=$this.find(".portfolio-categories a");var alreadyTriggered=false;$body.on("touchend",function(e){$(".mobile-true .rollover-content").removeClass("is-clicked");$(".mobile-true .rollover-active").removeClass("is-clicked");$(".mobile-true .rollover-active").parent("article").removeClass("is-clicked");});$this.on("touchstart",function(e){origY=e.originalEvent.touches[0].pageY;origX=e.originalEvent.touches[0].pageX;});$this.on("touchend",function(e){var touchEX=e.originalEvent.changedTouches[0].pageX,touchEY=e.originalEvent.changedTouches[0].pageY;if(origY==touchEY||origX==touchEX){if($this.hasClass("is-clicked")){if($this.parents(".ts-wrap").hasClass("ts-interceptClicks"))return;$thisSingleLink.each(function(){$thisTarget=$(this).attr("target")?$(this).attr("target"):"_self";});if($thisSingleLink.hasClass("project-details")||$thisSingleLink.hasClass("link")||$thisSingleLink.hasClass("project-link")){window.open($thisSingleLink.attr("href"),$thisTarget);return false;}else{if(!alreadyTriggered){alreadyTriggered=true;$thisSingleLink.trigger("click");alreadyTriggered=false;}
return false;}}else{e.preventDefault();$this.addClass("is-clicked");return false;}}});$this.find($thisCategory).click(function(e){e.stopPropagation();window.location.href=$thisCategory.attr('href');});$this.addClass("this-ready");});};$(".mobile-true .rollover-project.rollover-active, .mobile-true .rollover-active,  .mobile-true .buttons-on-img.rollover-active").touchFollowCurentLink();$.fn.touchRolloverPostClick=function(){return this.each(function(){var $this=$(this);var $thisSingleLink=$this.find(".post-thumbnail-rollover").first(),$thisCategory=$this.find(".entry-meta a, .fancy-date a, .fancy-categories a"),$thisOfTop=$this.find(".entry-excerpt").height()+$this.find(".post-details").height();$body.on("touchend",function(e){$(".mobile-true .post").removeClass("is-clicked");});$this.on("touchstart",function(e){origY=e.originalEvent.touches[0].pageY;origX=e.originalEvent.touches[0].pageX;});$this.on("touchend",function(e){var touchEX=e.originalEvent.changedTouches[0].pageX,touchEY=e.originalEvent.changedTouches[0].pageY;if(origY==touchEY||origX==touchEX){if($this.hasClass("is-clicked")){if($this.parents().hasClass("disable-layout-hover")){if(e.target.tagName.toLowerCase()==='a'){$(e.target).trigger("click");}else{}}}else{e.preventDefault();if(e.target.tagName.toLowerCase()==='a'){}
$(".mobile-ture .post").removeClass("is-clicked");$this.addClass("is-clicked");$this.parent().siblings().find(".post").removeClass("is-clicked");return false;};};});});};$(".mobile-true .content-rollover-layout-list.portfolio-shortcode .post, .mobile-true .gradient-overlay-layout-list.portfolio-shortcode .post").touchRolloverPostClick();$.fn.touchHoverImage=function(){return this.each(function(){var $img=$(this);if($img.hasClass("hover-ready")){return;}
$body.on("touchend",function(e){$(".mobile-true .rollover-content").removeClass("is-clicked");});var $this=$(this).find(".rollover-content"),thisPar=$this.parents(".wf-cell");$this.on("touchstart",function(e){origY=e.originalEvent.touches[0].pageY;origX=e.originalEvent.touches[0].pageX;});$this.on("touchend",function(e){var touchEX=e.originalEvent.changedTouches[0].pageX,touchEY=e.originalEvent.changedTouches[0].pageY;if(origY==touchEY||origX==touchEX){if($this.hasClass("is-clicked")){}else{$('.links-container > a',$this).on('touchend',function(e){e.stopPropagation();$this.addClass("is-clicked");});e.preventDefault();$(".mobile-true .buttons-on-img .rollover-content").removeClass("is-clicked");$this.addClass("is-clicked");return false;};};});$img.addClass("hover-ready");});};$(".mobile-true .buttons-on-img").touchHoverImage();$.fn.touchScrollerImage=function(){return this.each(function(){var $img=$(this);if($img.hasClass("hover-ready")){return;}
$body.on("touchend",function(e){$(".mobile-true .project-list-media").removeClass("is-clicked");});var $this=$(this),$thisSingleLink=$this.find("a.rollover-click-target").first(),$thisButtonLink=$this.find(".links-container");$this.on("touchstart",function(e){origY=e.originalEvent.touches[0].pageY;origX=e.originalEvent.touches[0].pageX;});$this.on("touchend",function(e){var touchEX=e.originalEvent.changedTouches[0].pageX,touchEY=e.originalEvent.changedTouches[0].pageY;if($this.parents(".ts-wrap").hasClass("ts-interceptClicks"))return;if(origY==touchEY||origX==touchEX){if($this.hasClass("is-clicked")){}else{if($thisSingleLink.length>0){$thisSingleLink.on("click",function(event){event.stopPropagation();if($(this).hasClass('go-to')){window.location.href=$(this).attr('href');}});$thisSingleLink.trigger("click");};if($thisButtonLink.length>0){$thisButtonLink.find(" > a ").each(function(){$(this).on("touchend",function(event){event.stopPropagation();$(this).trigger("click");});});}
e.preventDefault();$(".mobile-true .dt-owl-item").removeClass("is-clicked");$this.addClass("is-clicked");return false;};};});$img.addClass("hover-ready");});};$(".mobile-true .project-list-media").touchScrollerImage();$.fn.touchHoverLinks=function(){return this.each(function(){var $img=$(this);if($img.hasClass("hover-ready")){return;}
var $this=$(this);$this.on("touchend",function(e){if($this.parents(".ts-wrap").hasClass("ts-interceptClicks"))return;if($this.hasClass("is-clicked")){return;}else{if($this.hasClass("project-zoom")){$this.trigger("click");}else{window.location.href=$this.attr("href");return false;};$(".mobile-true .links-container > a").removeClass("is-clicked");$this.addClass("is-clicked");return false;};});$img.addClass("hover-ready");});};$(".mobile-true .dt-owl-item .links-container > a").touchHoverLinks();/*!Trigger albums click*/$.fn.triggerAlbumsClick=function(){return this.each(function(){var $this=$(this);if($this.hasClass("this-ready")){return;}
var $thisSingleLink=$this.find("a.rollover-click-target, a.dt-pswp-item").first(),$thisCategory=$this.find(".portfolio-categories a");if($thisSingleLink.length>0){$thisSingleLink.on("click",function(event){event.preventDefault();if($thisSingleLink.parents(".ts-wrap").hasClass("ts-interceptClicks"))return;if($(this).hasClass('go-to')){window.location.href=$(this).attr('href');}});var alreadyTriggered=false;$this.on("click",function(){if($this.parents(".ts-wrap").hasClass("ts-interceptClicks"))return;if(!alreadyTriggered){alreadyTriggered=true;$thisSingleLink.trigger("click");alreadyTriggered=false;}
return false;})
$this.find($thisCategory).click(function(e){e.stopPropagation();window.location.href=$thisCategory.attr('href');});}
$this.addClass("this-ready");});};$(".mobile-false .dt-albums-template .rollover-project, .mobile-false .dt-albums-shortcode .rollover-project, .mobile-false .dt-albums-template .buttons-on-img, .mobile-false .dt-albums-shortcode .buttons-on-img, .mobile-false .archive .type-dt_gallery .buttons-on-img").triggerAlbumsClick();/*!Trigger albums click*/$.fn.triggerAlbumsTouch=function(){return this.each(function(){var $this=$(this);if($this.hasClass("this-touch-ready")){return;}
var $thisSingleLink=$this.find("a.rollover-click-target, a.dt-pswp-item").first(),$thisCategory=$this.find(".portfolio-categories a");$body.on("touchend",function(e){$(".mobile-true .rollover-content").removeClass("is-clicked");});if($thisSingleLink.length>0){$thisSingleLink.on("click",function(event){event.preventDefault();if($thisSingleLink.parents(".ts-wrap").hasClass("ts-interceptClicks"))return;if($(this).hasClass('go-to')){window.location.href=$(this).attr('href');}});var alreadyTriggered=false;$this.on("touchstart",function(e){origY=e.originalEvent.touches[0].pageY;origX=e.originalEvent.touches[0].pageX;});$this.on("touchend",function(e){var touchEX=e.originalEvent.changedTouches[0].pageX,touchEY=e.originalEvent.changedTouches[0].pageY;if(origY==touchEY||origX==touchEX){if($this.parents(".ts-wrap").hasClass("ts-interceptClicks"))return;if(!alreadyTriggered){alreadyTriggered=true;$thisSingleLink.trigger("click");alreadyTriggered=false;}
return false;}})
$this.find($thisCategory).click(function(e){e.stopPropagation();window.location.href=$thisCategory.attr('href');});}
$this.addClass("this-touch-ready");});};$(".mobile-true .dt-albums-template .rollover-project, .mobile-true .dt-albums-shortcode .rollover-project, .mobile-true .dt-albums-template .buttons-on-img, .mobile-true .dt-albums-shortcode .buttons-on-img, .mobile-true .archive .type-dt_gallery .buttons-on-img").triggerAlbumsTouch();/*!Trigger rollover click*/$.fn.triggerHoverClick=function(){return this.each(function(){var $this=$(this);if($this.hasClass("click-ready")){return;}
var $thisSingleLink=$this.prev("a:not(.dt-single-pswp):not(.dt-pswp-item)").first(),$thisCategory=$this.find(".portfolio-categories a"),$thisLink=$this.find(".project-link"),$thisTarget=$thisLink.attr("target")?$thisLink.attr("target"):"_self",$targetClick;if($thisSingleLink.length>0){var alreadyTriggered=false;$this.on("click",function(e){if($this.parents(".ts-wrap").hasClass("ts-interceptClicks")||$this.parents('.owl-carousel').hasClass("ts-interceptClicks"))return;if($(".semitransparent-portfolio-icons").length>0||$(".accent-portfolio-icons").length>0){$targetClick=$(e.target).parent();}else{$targetClick=$(e.target);}
if($targetClick.hasClass("project-zoom")){}else{if(!alreadyTriggered){alreadyTriggered=true;$thisSingleLink.trigger("click");window.location.href=$thisSingleLink.attr('href');alreadyTriggered=false;}}
return false;})
$this.find($thisLink).click(function(e){e.stopPropagation();e.preventDefault();window.open($thisLink.attr("href"),$thisTarget);});$this.find($thisCategory).click(function(e){e.stopPropagation();window.location.href=$thisCategory.attr('href');});}
$this.addClass("click-ready");});};$(".mobile-false .rollover-project:not(.rollover-active) .rollover-content, .mobile-false .buttons-on-img:not(.rollover-active) .rollover-content").triggerHoverClick();});(function($){/*!
*
* jQuery collagePlus Plugin v0.3.2
* https://github.com/ed-lea/jquery-collagePlus
*
* Copyright 2012, Ed Lea twitter.com/ed_lea
*
* built for http://qiip.me
*
* Dual licensed under the MIT or GPL Version 2 licenses.
* http://www.opensource.org/licenses/mit-license.php
* http://www.opensource.org/licenses/GPL-2.0
*
*
* Heavily modified by Dream-Theme.com
*/$.fn.collagePlus=function(options){var defaults={'targetHeight':400,'albumWidth':this.width(),'padding':parseFloat(this.css('padding-left')),'images':this.children(),'fadeSpeed':"fast",'display':"inline-block",'effect':'default','direction':'vertical','allowPartialLastRow':false};var settings=$.extend({},defaults,options);return this.each(function(){var row=0,elements=[],rownum=1;settings.images.each(function(index){var $this=$(this),$img=($this.is("img"))?$this:$(this).find("img").not(".blur-effect").first();if($img.attr("width")!='undefined'&&$img.attr("height")!='undefined'){var w=(typeof $img.data("width")!='undefined')?$img.data("width"):$img.attr("width"),h=(typeof $img.data("height")!='undefined')?$img.data("height"):$img.attr("height");}
else{var w=(typeof $img.data("width")!='undefined')?$img.data("width"):$img.width(),h=(typeof $img.data("height")!='undefined')?$img.data("height"):$img.height();}
var imgParams=getImgProperty($img);$img.data("width",w);$img.data("height",h);var nw=Math.ceil(w/h*settings.targetHeight),nh=Math.ceil(settings.targetHeight);elements.push([this,nw,nh,imgParams['w'],imgParams['h']]);row+=nw+imgParams['w']+settings.padding;if(row>settings.albumWidth&&elements.length!=0){resizeRow(elements,row,settings,rownum);delete row;delete elements;row=0;elements=[];rownum+=1;}
if(settings.images.length-1==index&&elements.length!=0){resizeRow(elements,row,settings,rownum);delete row;delete elements;row=0;elements=[];rownum+=1;}});$(this).trigger("jgDone");});function resizeRow(obj,row,settings,rownum){var imageExtras=(settings.padding*obj.length)+(obj.length*obj[0][3]),albumWidthAdjusted=settings.albumWidth-imageExtras,overPercent=albumWidthAdjusted/(row-imageExtras),trackWidth=imageExtras,lastRow=(row<settings.albumWidth?true:false);for(var i=0;i<obj.length;i++){var $obj=$(obj[i][0]),fw=Math.floor(obj[i][1]*overPercent),fh=Math.floor(obj[i][2]*overPercent),isNotLast=!!((i<obj.length-1));if(settings.allowPartialLastRow===true&&lastRow===true){fw=obj[i][1];fh=obj[i][2];}
trackWidth+=fw;var $img=($obj.is("img"))?$obj:$obj.find("img").not(".blur-effect").first();$img.width(fw);if(!$obj.is("img")){$obj.width(fw+obj[i][3]);}
$img.height(fh);if(!$obj.is("img")){$obj.height(fh+obj[i][4]);}
if(settings.allowPartialLastRow===false&&lastRow===true){applyModifications($obj,isNotLast,"none");}
else{applyModifications($obj,isNotLast,settings.display);};}}
function applyModifications($obj,isNotLast,settingsDisplay){var css={'display':settingsDisplay,'vertical-align':"bottom",'overflow':"hidden"};return $obj.css(css);}
function getImgProperty(img){$img=$(img);var params=new Array();params["w"]=(parseFloat($img.css("border-left-width"))+parseFloat($img.css("border-right-width")));params["h"]=(parseFloat($img.css("border-top-width"))+parseFloat($img.css("border-bottom-width")));return params;}};var jgCounter=0;$(".jg-container").each(function(){jgCounter++;var $jgContainer=$(this),$jgItemsPadding=$jgContainer.attr("data-padding"),$jgItems=$jgContainer.find(".wf-cell");$jgContainer.attr("id","jg-container-"+jgCounter+"");$("<style type='text/css'>"+' .content #jg-container-'+jgCounter+' .wf-cell'+'{padding:'+$jgItemsPadding+';}'+' .content #jg-container-'+jgCounter+'.wf-container'+'{'+'margin:'+'-'+$jgItemsPadding+';}'+' .content .full-width-wrap #jg-container-'+jgCounter+'.wf-container'+'{'+'margin-left:'+$jgItemsPadding+'; '+'margin-right:'+$jgItemsPadding+'; '+'margin-top:'+'-'+$jgItemsPadding+'; '+'margin-bottom:'+'-'+$jgItemsPadding+';}'+"</style>").insertAfter($jgContainer);var layzrJGridTimer;$jgContainer.on("jgDone",function(){var layzrJGrid=new Layzr({selector:'.jgrid-lazy-load',attr:'data-src',attrSrcSet:'data-srcset',retinaAttr:'data-src-retina',threshold:0,before:function(){this.setAttribute("sizes",this.width+"px");this.style.willChange='opacity';},callback:function(){this.classList.add("jgrid-layzr-loaded");var $this=$(this);$this.one('webkitTransitionEnd otransitionend oTransitionEnd msTransitionEnd transitionend',function(e){clearTimeout(layzrJGridTimer);layzrJGridTimer=setTimeout(function(){$this.parent().removeClass("layzr-bg");$this.css("will-change",'auto');},200)});}});});});$.fn.collage=function(args){return this.each(function(){var $this=$(this);var $jgContainer=$(this),$jgItemsPadding=$jgContainer.attr("data-padding"),$jgItems=$jgContainer.find(".wf-cell");var jgPadding=parseFloat($jgItems.first().css('padding-left'))+parseFloat($jgItems.first().css('padding-right')),jgTargetHeight=parseInt($jgContainer.attr("data-target-height")),jdPartRow=true;if($jgContainer.attr("data-part-row")=="false"){jdPartRow=false;};if($jgContainer.parent(".full-width-wrap").length){var jgAlbumWidth=$jgContainer.parents(".full-width-wrap").width()-parseInt($jgItemsPadding)*2;}else{var jgAlbumWidth=$jgContainer.parent().width()+parseInt($jgItemsPadding)*2;}
var $jgCont={'albumWidth':jgAlbumWidth,'targetHeight':jgTargetHeight,'padding':jgPadding,'allowPartialLastRow':jdPartRow,'fadeSpeed':2000,'effect':'effect-1','direction':'vertical'};$.extend($jgCont,args);dtGlobals.jGrid=$jgCont;$jgContainer.collagePlus($jgCont);$jgContainer.css({'width':jgAlbumWidth});});};$(window).on("debouncedresize",function(){$(".jg-container").not('.jgrid-shortcode').collage();$(".jgrid-shortcode").each(function(){var $this=$(this);var $visibleItems=$this.data('visibleItems');if($visibleItems){$this.collage({'images':$visibleItems});}else{$this.collage();}});}).trigger("debouncedresize");})(jQuery);